package tradly.social.domain.entities

open class Product(
    var title: String = Constant.EMPTY,
    var description: String? = Constant.EMPTY,
    var store: Store? = Store(),
    var location: GeoPoint = GeoPoint(),
    var priceType: Int? = 0,
    var deliveryDetails: String? = null,
    var condition: Int = 0,
    var category: Category? = null,
    var offerPercent: Int = 0,
    var offerPrice: Price = Price(),
    var listPrice: Price = Price(),
    var displayPrice:String = Constant.EMPTY,
    var displayOffer:String = Constant.EMPTY,
    var quantityPerUnit: Int? = 0,
    var maxQuantity: Int = 0,
    var images: List<String> = mutableListOf(),
    var storeName: String? = Constant.EMPTY,
    var storePic: String? = Constant.EMPTY,
    var storeAddress: String? = Constant.EMPTY,
    override var id: String = Constant.EMPTY,
    override var createdAt: Long = 0,
    override var updatedAt: Long = 0,
    var sets:List<Set>?=null,
    val variants: List<Variant> = emptyList(),
    var isProductInCart: Boolean = false,
    var variantsCount:Int=0,
    var setsCount:Int=0,
    var stock:Int=0,
    var variant: Variant?=null,
    var set: Set? =null,
    var currencyId:Int = 0,
    var categoryIds:List<Int> = listOf(),
    var status:Int = 0,
    var attributes:List<Attribute> = listOf<Attribute>(),
    var inStock:Boolean = false,
    var isLiked:Boolean = false,
    var tags:List<Tag> = listOf(),
    var isActive: Boolean = false,
    var address:Address? = null,
    var shipping: Shipping = Shipping(),
    var negotiation: Negotiation?=null,
    var rating:Rating?=null,
    var startAt:Long = 0,
    var endAt:Long = 0,
    var likes:Int = 0

) : BaseInfo
