package tradly.social.common.network.parseHelper

class ParseCloudFunction {
    companion object{
        const val GET_CATEGORIES = "categories"
        const val INIT_REGIGTER = "appInitRegister"
        const val APP_REGISTER = "appRegister"
        const val APP_INIT_LOGIN = "appInitLogin"
        const val APP_LOGIN = "appLogin"
        const val ADD_PRODUCT = "addProduct"
        const val PRODUCTS = "products"
        const val GROUPS = "groups"
        const val APP_HOME = "appHome"
        const val STORES = "stores"
        const val PRODUCT = "product"
        const val UPLOAD_URL = "uploadURL"
        const val ADD_CART = "addToCart"
        const val CART = "cart"
        const val GET_ADDRESS = "getAddress"
    }

    object Params{
        const val CATEGORY_ID ="category_id"
        const val DOMAIN = "domain"
        const val EMAIL = "e"
        const val COUNTRY = "country"
        const val CODE = "c"
        const val VERIFICATION_ID = "verify_id"
        const val PASSWORD = "p"
        const val MOBILE = "m"
        const val FULL_NAME = "n"
        const val TITLE = "title"
        const val DESCRIPTION = "description"
        const val PRICE_TYPE = "price_type"
        const val CONDITION = "condition"
        const val QTY_PER_UNIT = "quantity_per_unit"
        const val LIST_PRICE = "list_price"
        const val MAX_QNTY = "max_quantity"
        const val TAGS = "tags"
        const val GROUP_LIST= "groups"
        const val IMAGES = "images"
        const val SCOPE = "scope"
        const val IS_MY_GROUP = "my_group"
        const val KEY = "key"
        const val PAGE = "page"
        const val PRODUCT_ID = "product_id"
        const val STORE_ID ="store_id"
        const val GROUP_ID = "group_id"
        const val MAX_RESULTS = "max_results"
        const val SORT = "sort"
        const val MY_PRODUCTS = "my_products"
        const val FILES = "files"
        const val TYPE = "type"
        const val NAME = "name"
        const val ID ="id"
        const val QUANTITY = "quantity"
        const val LATITUDE = "latitude"
        const val LONGITUDE = "longitude"
    }
}